# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=eDP-1,1920x1080@144,0x0,1,bitdepth,10 # Internal laptop monitor
# monitor=desc:AOC 2270W ASZKA1A003151,1920x1080,0x0,1 # External second monitor


## GF tv
monitor=desc:Vestel Elektronik Sanayi ve Ticaret A. S. 39FHD_LCD_TV,highrr,auto,1.3 #Special setting for a TV

## RS monitor setup ON SITE
#

monitor=desc:Dell Inc. DELL P2723D 13FFFZ3,2560x1440@60,-2560x0,1
monitor=desc:Hewlett Packard HP Z24n CN464713YR,1920x1200@60,1920x0,1
