windowrulev2 = stayfocused, title:^()$,class:^(steam)$
windowrulev2 = minsize 1 1, title:^()$,class:^(steam)$
windowrule = float, title:^(Volume Control)$
windowrule = move 100%-710 50, title:^(Volume Control)$
windowrule = size 700 400, title:^(Volume Control)$
windowrule = float, title:^(nwg-look)$
windowrule = center, title:^(nwg-look)$
windowrule = float, class:^(Kuro)$
windowrulev2 = immediate, class:^(cs2)$
windowrulev2= noblur,class:^()$,title:^()$
windowrulev2= float, title:(Open Folder)$
windowrulev2= size 714 742, title:(Open Folder)$
windowrulev2= float, title:(Friends List)$
